trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-Dmaven.test.skip=true'
    goals: 'clean install'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'

- script: |
    docker build -t your-image-name:$(Build.BuildId) .
  displayName: 'Build Docker image'
  shell: powershell
