trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-Dmaven.test.skip=true'
    goals: 'clean install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: 'your-image-name:$(Build.BuildId)'
